import { StyleSheet } from "react-native";
import {
  BRAND_DANGER,
  brandDangerBg,
  brandDangerBorder,
  brandPrimary,
  brandSecondary,
  brandTintBg,
  neutral,
} from "../../../shared/theme/color";
import { appTypography } from "../../../shared/utils/typography";

const userProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: neutral.canvasMuted,
  },
  contentContainer: {
    paddingBottom: 100,
  },
  headerBackground: {
    height: 180,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 40,
  },
  headerTitle: {
    ...appTypography.dialogTitle,
    color: neutral.surface,
    marginBottom: 10,
  },
  profileCard: {
    backgroundColor: neutral.surface,
    marginHorizontal: 20,
    marginTop: -50,
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  avatarContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: neutral.avatarPlaceholder,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    borderWidth: 4,
    borderColor: neutral.surface,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatarText: {
    ...appTypography.displayLarge,
    color: brandPrimary,
  },
  userName: {
    ...appTypography.profileName,
    color: neutral.textBody,
    marginBottom: 5,
  },
  userEmail: {
    ...appTypography.body,
    color: neutral.textSecondary,
    marginBottom: 10,
  },
  userRoleContainer: {
    backgroundColor: brandTintBg,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 15,
  },
  userRole: {
    ...appTypography.body,
    color: brandSecondary,
    fontWeight: "600",
  },
  sectionContainer: {
    marginTop: 25,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    ...appTypography.sectionHeading,
    fontWeight: "600",
    color: neutral.textSecondary,
    marginBottom: 10,
    marginLeft: 10,
    textTransform: "uppercase",
  },
  menuItem: {
    backgroundColor: neutral.surface,
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: neutral.tileMuted,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  menuContent: {
    flex: 1,
  },
  menuLabel: {
    ...appTypography.modalListItem,
    fontWeight: "500",
    color: neutral.textBody,
  },
  menuDescription: {
    ...appTypography.secondary,
    color: neutral.textMuted,
    marginTop: 2,
  },
  logoutButton: {
    marginTop: 30,
    marginHorizontal: 20,
    backgroundColor: brandDangerBg,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: brandDangerBorder,
  },
  logoutText: {
    ...appTypography.dialogButton,
    color: BRAND_DANGER,
    fontWeight: "700",
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  infoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: neutral.tileMuted,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    ...appTypography.itemTitle,
    color: neutral.textBody,
    marginBottom: 5,
  },
  infoValue: {
    ...appTypography.body,
    color: neutral.textSecondary,
  },
});

export default userProfileStyles;
