import { StyleSheet } from "react-native";

/**
 * Styles cho màn Staff IoT (list theo nhà).
 * Mục tiêu: tách style ra file riêng để `staffIotList.tsx` dễ đọc và dễ bảo trì.
 */
export const staffIotStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  backBtn: { padding: 8, marginRight: 8 },
  topTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#1F2937",
    flex: 1,
  },

  scroll: { paddingBottom: 24 },

  houseCard: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#2563EB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  houseLabel: { fontSize: 12, color: "#6B7280", marginBottom: 6, fontWeight: "600" },
  houseName: { fontSize: 16, color: "#111827", fontWeight: "700" },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },
  // Backward-compat alias (màn list đang dùng tên này)
  sectionTitlePlain: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },

  loadingRow: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  loadingText: { fontSize: 13, color: "#6B7280" },

  chipRow: { paddingHorizontal: 16, paddingRight: 16, flexDirection: "row", gap: 10 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  chipActive: { backgroundColor: "#2563EB", borderColor: "#2563EB" },
  chipText: { fontSize: 13, fontWeight: "700", color: "#6B7280" },
  chipTextActive: { color: "#fff" },

  // Header row cho section "Thiết bị": chip + nút "+"
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  // Row chứa chip danh mục (Tất cả/Controller/Node)
  kindRow: {
    flexDirection: "row",
    gap: 10,
    flex: 1,
  },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },

  // ---------------- Modal add menu (Controller/Node) ----------------
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingTop: 14,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 10,
  },
  modalItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#fff",
    marginBottom: 10,
  },
  modalItemIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#E0E7FF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  modalItemTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  modalItemSub: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
    lineHeight: 16,
  },
  modalCancel: {
    marginTop: 2,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalCancelText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },

  areaCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
  },
  areaLeftAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: "#2563EB",
  },
  areaName: { fontSize: 15, fontWeight: "800", color: "#111827", marginBottom: 4 },
  areaMeta: { fontSize: 12, color: "#6B7280", lineHeight: 16 },

  empty: {
    marginHorizontal: 16,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  emptyTitle: { fontSize: 14, fontWeight: "800", color: "#111827", marginBottom: 6 },
  emptySub: { fontSize: 13, color: "#6B7280", lineHeight: 18 },

  groupHeader: {
    marginHorizontal: 16,
    marginTop: 6,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  groupDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#2563EB" },
  groupTitle: { fontSize: 13, fontWeight: "800", color: "#374151" },

  deviceCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
  },
  deviceLeftAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
  deviceInfo: { flex: 1, minWidth: 0, marginRight: 12 },
  deviceName: { fontSize: 15, fontWeight: "800", color: "#111827" },
  deviceMeta: { fontSize: 12, color: "#6B7280", marginTop: 4 },
  deviceRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusBadgeText: { fontSize: 12, fontWeight: "900" },

  detachBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  detachBtnText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#DC2626",
  },

  // =========================================================
  // Flow: Provision (select area) + QR scan + Waiting
  // =========================================================

  flowTopBar: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  flowBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  flowTopTitle: { flex: 1, fontSize: 16, fontWeight: "900", color: "#111827" },
  flowScroll: { paddingTop: 12, paddingBottom: 24 },
  flowHouseCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 14,
  },
  flowHouseLabel: { fontSize: 12, color: "#6B7280", fontWeight: "700" },
  flowHouseName: { marginTop: 6, fontSize: 16, fontWeight: "900", color: "#111827" },
  flowSection: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 14,
  },
  flowSectionTitle: { fontSize: 14, fontWeight: "900", color: "#111827" },
  flowSectionSub: { marginTop: 4, fontSize: 12, lineHeight: 16, color: "#6B7280" },
  flowLoadingRow: { marginTop: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  flowLoadingText: { fontSize: 12, color: "#6B7280", fontWeight: "700" },
  flowEmptyCard: { marginTop: 10, padding: 12, borderRadius: 12, backgroundColor: "#F9FAFB" },
  flowEmptyTitle: { fontSize: 13, fontWeight: "800", color: "#111827" },
  flowAreaGrid: { marginTop: 10, flexDirection: "row", flexWrap: "wrap", gap: 10 },
  flowAreaChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    minWidth: "48%",
    flexGrow: 1,
  },
  flowAreaChipActive: { backgroundColor: "#2563EB", borderColor: "#1D4ED8" },
  flowAreaChipText: { fontSize: 13, fontWeight: "900", color: "#111827" },
  flowAreaChipTextActive: { color: "#fff" },
  flowAreaChipHint: { marginTop: 4, fontSize: 11, color: "#16A34A", fontWeight: "800" },
  flowPrimaryBtn: {
    marginTop: 10,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
  },
  flowPrimaryBtnText: { fontSize: 14, fontWeight: "900", color: "#fff" },

  // WiFi list box (giới hạn chiều cao danh sách)
  wifiListBox: {
    marginTop: 10,
    maxHeight: 320,
  },

  // QR Scan overlay
  qrContainer: { flex: 1, backgroundColor: "#000" },
  qrPermissionWrap: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: "#000" },
  qrPermissionText: { color: "#fff", fontSize: 14, fontWeight: "800", textAlign: "center", marginBottom: 12 },
  qrOverlay: { position: "absolute", left: 0, right: 0, bottom: 0, padding: 16, gap: 10 },
  qrCard: {
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  qrCardTitle: { color: "#fff", fontSize: 14, fontWeight: "900" },
  qrCardSub: { marginTop: 6, color: "#E5E7EB", fontSize: 12, lineHeight: 16 },
  qrCancelBtn: {
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  qrCancelText: { color: "#fff", fontSize: 14, fontWeight: "900" },

  // Waiting screen
  waitInfoCard: {
    margin: 16,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  waitRowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  waitLabel: { fontSize: 12, fontWeight: "800", color: "#6B7280" },
  waitValue: { flex: 1, textAlign: "right", fontSize: 12, fontWeight: "900", color: "#111827" },
  waitWrap: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 24, paddingBottom: 24 },
  waitTitle: { marginTop: 14, fontSize: 16, fontWeight: "900", color: "#111827", textAlign: "center" },
  waitSub: { marginTop: 8, fontSize: 13, lineHeight: 18, color: "#6B7280", textAlign: "center" },
  waitStepList: {
    marginTop: 18,
    alignSelf: "stretch",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  waitStepRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  waitStepDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#CBD5E1" },
  waitStepText: { fontSize: 13, fontWeight: "800", color: "#64748B" },
  waitStepTextActive: { color: "#111827" },
  waitRetryBtn: {
    marginTop: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  waitRetryText: { fontSize: 14, fontWeight: "900", color: "#111827" },
});

