import { StyleSheet } from "react-native";
import {
  BRAND_DANGER,
  brandFocusBorder,
  brandPrimary,
  neutral,
} from "../../../../shared/theme/color";
import { appTypography } from "../../../../shared/utils";

/**
 * Styles cho màn Staff IoT (list theo nhà).
 * Mục tiêu: tách style ra file riêng để `staffIotList.tsx` dễ đọc và dễ bảo trì.
 */
export const staffIotStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: neutral.backgroundElevated },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: neutral.surface,
    borderBottomWidth: 1,
    borderBottomColor: neutral.border,
  },
  backBtn: { padding: 8 },

  scroll: { paddingBottom: 24 },

  houseCard: {
    backgroundColor: neutral.surface,
    margin: 16,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: brandPrimary,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  houseLabel: {
    ...appTypography.caption,
    color: neutral.textSecondary,
    marginBottom: 6,
    fontWeight: "600",
  },
  houseName: { ...appTypography.sectionHeading, color: neutral.text },

  sectionTitle: {
    ...appTypography.sectionHeading,
    fontWeight: "800",
    color: neutral.text,
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },
  // Backward-compat alias (màn list đang dùng tên này)
  sectionTitlePlain: {
    ...appTypography.sectionHeading,
    fontWeight: "800",
    color: neutral.text,
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },

  loadingRow: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 14,
    borderRadius: 12,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  loadingText: { ...appTypography.secondary, color: neutral.textSecondary },

  chipRow: { paddingHorizontal: 16, paddingRight: 16, flexDirection: "row", gap: 10 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  chipActive: { backgroundColor: brandPrimary, borderColor: brandPrimary },
  chipText: { ...appTypography.chip, fontWeight: "700", color: neutral.textSecondary },
  chipTextActive: { color: neutral.surface },

  // Header row cho section "Thiết bị": chip + nút "+"
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  // Row chứa chip danh mục (Tất cả/Controller/Node)
  kindRow: {
    flexDirection: "row",
    gap: 10,
    flex: 1,
  },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: brandPrimary,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },

  areaCard: {
    backgroundColor: neutral.surface,
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: neutral.border,
    overflow: "hidden",
  },
  areaLeftAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: brandPrimary,
  },
  areaName: {
    ...appTypography.listTitle,
    fontWeight: "800",
    color: neutral.text,
    marginBottom: 4,
  },
  areaMeta: { ...appTypography.caption, color: neutral.textSecondary },

  empty: {
    marginHorizontal: 16,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  emptyTitle: {
    ...appTypography.itemTitle,
    fontWeight: "800",
    color: neutral.text,
    marginBottom: 6,
  },
  emptySub: { ...appTypography.secondary, color: neutral.textSecondary },

  groupHeader: {
    marginHorizontal: 16,
    marginTop: 6,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  groupDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: brandPrimary },
  groupTitle: {
    ...appTypography.secondary,
    fontWeight: "800",
    color: neutral.textBody,
  },

  deviceCard: {
    backgroundColor: neutral.surface,
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: neutral.border,
    overflow: "hidden",
  },
  deviceLeftAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
  deviceInfo: { flex: 1, minWidth: 0, marginRight: 12 },
  deviceName: {
    ...appTypography.listTitle,
    fontWeight: "800",
    color: neutral.text,
  },
  deviceMeta: { ...appTypography.caption, color: neutral.textSecondary, marginTop: 4 },
  deviceRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusBadgeText: { ...appTypography.caption, fontWeight: "900" },

  detachBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.warningBorderLight,
  },
  detachBtnText: {
    ...appTypography.caption,
    fontWeight: "800",
    color: BRAND_DANGER,
  },

  /** Dòng phụ dưới tên trên thẻ list (gợi ý controller vs node). */
  deviceHint: {
    ...appTypography.caption,
    color: neutral.textSecondary,
    marginTop: 4,
    lineHeight: 18,
  },
  /** Vùng bấm mở chi tiết (trừ nút Tháo). */
  deviceRowPressable: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },

  detailScroll: { paddingBottom: 24 },
  detailCard: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: neutral.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: neutral.border,
    padding: 14,
  },
  detailRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: neutral.borderMuted,
  },
  detailRowLast: {
    borderBottomWidth: 0,
  },
  detailLabel: {
    ...appTypography.caption,
    fontWeight: "700",
    color: neutral.textSecondary,
    marginBottom: 4,
  },
  detailValue: {
    ...appTypography.secondary,
    color: neutral.text,
    lineHeight: 22,
  },
  detailEmpty: {
    marginHorizontal: 16,
    marginTop: 24,
    padding: 16,
    ...appTypography.secondary,
    color: neutral.textSecondary,
    textAlign: "center",
  },

  // =========================================================
  // Flow: Provision (select area) + QR scan + Waiting
  // =========================================================

  flowTopBar: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: neutral.surface,
    borderBottomWidth: 1,
    borderBottomColor: neutral.border,
  },
  flowBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: neutral.background,
    alignItems: "center",
    justifyContent: "center",
  },
  flowTopTitle: {
    flex: 1,
    ...appTypography.sectionHeading,
    fontWeight: "900",
    color: neutral.text,
  },
  flowScroll: { paddingTop: 12, paddingBottom: 24 },
  flowHouseCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 14,
    padding: 14,
  },
  flowHouseLabel: {
    ...appTypography.caption,
    color: neutral.textSecondary,
    fontWeight: "700",
  },
  flowHouseName: {
    marginTop: 6,
    ...appTypography.sectionHeading,
    fontWeight: "900",
    color: neutral.text,
  },
  flowSection: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 14,
    padding: 14,
  },
  flowSectionTitle: {
    ...appTypography.body,
    fontWeight: "900",
    color: neutral.text,
  },
  flowSectionSub: {
    marginTop: 4,
    ...appTypography.caption,
    color: neutral.textSecondary,
  },
  flowLoadingRow: { marginTop: 10, flexDirection: "row", alignItems: "center", gap: 10 },
  flowLoadingText: {
    ...appTypography.captionStrong,
    color: neutral.textSecondary,
  },
  flowEmptyCard: { marginTop: 10, padding: 12, borderRadius: 12, backgroundColor: neutral.backgroundSubtle },
  flowEmptyTitle: {
    ...appTypography.secondary,
    fontWeight: "800",
    color: neutral.text,
  },
  flowAreaGrid: { marginTop: 10, flexDirection: "row", flexWrap: "wrap", gap: 10 },
  flowAreaChip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: neutral.border,
    backgroundColor: neutral.backgroundSubtle,
    minWidth: "48%",
    flexGrow: 1,
  },
  flowAreaChipActive: { backgroundColor: brandPrimary, borderColor: brandFocusBorder },
  flowAreaChipText: {
    ...appTypography.chip,
    fontWeight: "900",
    color: neutral.text,
  },
  flowAreaChipTextActive: { color: neutral.surface },
  flowAreaChipHint: {
    marginTop: 4,
    ...appTypography.hint,
    color: brandPrimary,
    fontWeight: "800",
  },
  flowPrimaryBtn: {
    marginTop: 10,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: brandPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  flowPrimaryBtnText: {
    ...appTypography.buttonLabel,
    fontWeight: "900",
    color: neutral.surface,
  },

  // WiFi list box (giới hạn chiều cao danh sách)
  wifiListBox: {
    marginTop: 10,
    maxHeight: 320,
  },

  // QR Scan overlay
  qrContainer: { flex: 1, backgroundColor: neutral.black },
  qrPermissionWrap: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: neutral.black },
  qrPermissionText: {
    ...appTypography.body,
    color: neutral.surface,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 12,
  },
  /** Full-screen mask; dùng kèm các lớp dim tính toán trong màn QR. */
  qrScanMaskRoot: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: "box-none" as const,
  },
  qrDimLayer: {
    position: "absolute",
    backgroundColor: "rgba(0,0,0,0.58)",
  },
  qrFrameOutline: {
    position: "absolute",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.95)",
    borderRadius: 12,
    backgroundColor: "transparent",
  },
  qrTopBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  qrBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  qrBottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  qrCancelBtn: {
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  qrCancelText: {
    ...appTypography.buttonLabel,
    color: neutral.surface,
    fontWeight: "900",
  },

  // Waiting screen
  waitInfoCard: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  waitRowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  waitLabel: {
    ...appTypography.caption,
    fontWeight: "800",
    color: neutral.textSecondary,
  },
  waitValue: {
    flex: 1,
    textAlign: "right",
    ...appTypography.caption,
    fontWeight: "900",
    color: neutral.text,
  },
  waitWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 24,
  },
  waitTitle: {
    marginTop: 14,
    ...appTypography.sectionHeading,
    fontWeight: "900",
    color: neutral.text,
    textAlign: "center",
  },
  waitSub: {
    marginTop: 8,
    ...appTypography.secondary,
    color: neutral.textSecondary,
    textAlign: "center",
  },
  waitStepList: {
    marginTop: 18,
    alignSelf: "stretch",
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  waitStepRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  waitStepDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: neutral.slate300 },
  waitStepText: {
    ...appTypography.secondary,
    fontWeight: "800",
    color: neutral.slate500,
  },
  waitStepTextActive: { color: neutral.text },
  waitRetryBtn: {
    marginTop: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: neutral.background,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  waitRetryText: {
    ...appTypography.buttonLabel,
    fontWeight: "900",
    color: neutral.text,
  },

  // WiFi password input: nhét icon show/hide ngay trong khung input
  wifiPasswordInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 10,
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 12,
    overflow: "hidden",
    paddingHorizontal: 12,
    justifyContent: "space-between",
  },
  wifiPasswordInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 0,
    ...appTypography.body,
    color: neutral.text,
    fontWeight: "800",
  },
  wifiPasswordToggleBtn: {
    paddingHorizontal: 6,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
});

