import { StyleSheet } from "react-native";
import { brandPrimary, brandSecondary, neutral } from "../../../shared/theme/color";
import { appTypography } from "../../../shared/utils/typography";

const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 48,
  },
  logoWrapper: {
    width: 120,
    height: 120,
    borderRadius: 24,
    backgroundColor: neutral.surface,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  logoImage: {
    width: 96,
    height: 96,
    resizeMode: "contain",
  },
  brandTitle: {
    ...appTypography.loginBrandMark,
    color: neutral.surface,
    marginBottom: 8,
    letterSpacing: 2,
  },
  subtitle: {
    ...appTypography.sectionHeading,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "500",
  },
  form: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: neutral.surface,
    borderRadius: 24,
    padding: 32,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  title: {
    ...appTypography.loginScreenTitle,
    marginBottom: 12,
    color: neutral.slate900,
    textAlign: "center",
  },
  description: {
    ...appTypography.dialogMessage,
    color: neutral.slate500,
    textAlign: "center",
    marginBottom: 32,
  },
  button: {
    alignSelf: "stretch",
    width: "100%",
    backgroundColor: brandSecondary,
    paddingVertical: 16,
    paddingHorizontal: 22,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: brandSecondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    ...appTypography.loginPrimaryCta,
    color: neutral.surface,
    letterSpacing: 0.5,
    textAlign: "center",
    flexShrink: 1,
    width: "100%",
  },
  languageContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 32,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 20,
    padding: 4,
    marginHorizontal: 24,
  },
  languageButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 16,
    marginHorizontal: 4,
  },
  languageButtonActive: {
    backgroundColor: neutral.surface,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  languageText: {
    color: "rgba(255, 255, 255, 0.8)",
    ...appTypography.body,
    fontWeight: "600",
  },
  languageTextActive: {
    color: brandSecondary,
    fontWeight: "700",
  },
  webViewOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    /* Trùng đầu gradient Keycloak / login — tránh viền trắng quanh WebView */
    backgroundColor: brandPrimary,
    zIndex: 100,
  },
  webViewHeader: {
    height: 56,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: neutral.slate200,
    backgroundColor: neutral.surface,
  },
  webViewCloseText: {
    ...appTypography.dialogMessage,
    fontWeight: "600",
    color: brandSecondary,
  },
  webViewLoadingOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: neutral.surface,
  },
});

export default loginStyles;
