import { StyleSheet } from "react-native";

const loginStyles = StyleSheet.create({
    container: {
        flex: 1,
        width: "100%",
    },
    content: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 24,
    },
    logoContainer: {
        alignItems: "center",
        marginBottom: 48,
    },
    logoWrapper: {
        width: 120,
        height: 120,
        borderRadius: 24,
        backgroundColor: "#ffffff",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
    },
    logoImage: {
        width: 96,
        height: 96,
        resizeMode: "contain",
    },
    brandTitle: {
        fontSize: 32,
        fontWeight: "700",
        color: "#ffffff",
        marginBottom: 8,
        letterSpacing: 2,
    },
    subtitle: {
        fontSize: 16,
        color: "rgba(255, 255, 255, 0.9)",
        fontWeight: "500",
    },
    form: {
        width: "100%",
        maxWidth: 400,
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 32,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 10,
    },
    title: {
        fontSize: 28,
        fontWeight: "700",
        marginBottom: 12,
        color: "#0f172a",
        textAlign: "center",
    },
    description: {
        fontSize: 15,
        color: "#64748b",
        textAlign: "center",
        marginBottom: 32,
        lineHeight: 22,
    },
    button: {
        backgroundColor: "#1e88e5",
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: "center",
        shadowColor: "#1e88e5",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    buttonText: {
        color: "#ffffff",
        fontSize: 17,
        fontWeight: "600",
        letterSpacing: 0.5,
    },
    languageContainer: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 32,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        borderRadius: 20,
        padding: 4,
        marginHorizontal: 24,
    },
    languageButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 16,
        marginHorizontal: 4,
    },
    languageButtonActive: {
        backgroundColor: "#ffffff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    languageText: {
        color: "rgba(255, 255, 255, 0.8)",
        fontSize: 14,
        fontWeight: "600",
    },
    languageTextActive: {
        color: "#1e88e5",
        fontWeight: "700",
    },
    webViewOverlay: {
        position: "absolute",
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        backgroundColor: "#ffffff",
    },
    webViewHeader: {
        height: 56,
        justifyContent: "center",
        alignItems: "flex-end",
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
        backgroundColor: "#ffffff",
    },
    webViewCloseText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#1e88e5",
    },
    webViewLoadingOverlay: {
        position: "absolute",
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#ffffff",
    },
});

export default loginStyles;