import { StyleSheet } from "react-native";
import { brandPrimary, brandTintBg, neutral } from "../../../../shared/theme/color";
import { staffFormShape } from "../../../../shared/styles/staffFormShape";

/**
 * Style cho màn xác nhận kiểm định (InspectionConfirmScreen).
 */
export const inspectionConfirmStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: neutral.canvasMuted },
  scroll: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  sectionCard: {
    backgroundColor: neutral.surface,
    borderRadius: staffFormShape.radiusSurface,
    padding: 18,
    marginBottom: 16,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderCurve: "continuous",
  },
  cardFieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: neutral.slate500,
    marginBottom: 8,
  },
  cardFieldLabelInline: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: neutral.text,
    paddingRight: 8,
  },
  houseRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: staffFormShape.radiusControl,
    backgroundColor: neutral.backgroundSubtle,
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    borderCurve: "continuous",
  },
  houseValue: {
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
    color: neutral.text,
  },
  muted: { color: neutral.slate500, marginBottom: 8 },
  photoRow: { minHeight: 88 },
  photoRowContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 4,
  },
  thumbWrap: {
    marginRight: 8,
    borderRadius: staffFormShape.radiusControl,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    borderCurve: "continuous",
  },
  thumb: {
    width: 88,
    height: 88,
    backgroundColor: brandTintBg,
  },
  damageRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
    gap: 12,
  },
  bannerLoading: { marginVertical: 12 },
  bannerBox: { marginTop: 4, marginBottom: 8 },
  notesInput: {
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    borderRadius: staffFormShape.radiusControl,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: neutral.surface,
    color: neutral.text,
    fontSize: 15,
    borderCurve: "continuous",
  },
  notes: { minHeight: 100, textAlignVertical: "top" },
  deduction: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: neutral.border,
    fontSize: 15,
    fontWeight: "700",
    color: neutral.text,
  },
  submitBtn: {
    marginTop: 8,
    borderRadius: staffFormShape.radiusControl,
    backgroundColor: brandPrimary,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    shadowColor: brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 5,
  },
  submitBtnDisabled: { opacity: 0.7 },
  submitBtnText: {
    color: neutral.surface,
    fontSize: 15,
    fontWeight: "800",
  },
});
