import { StyleSheet } from "react-native";
import {
  brandPrimary,
  brandSecondary,
  brandTintBg,
  neutral,
} from "../../../../shared/theme/color";
import { staffFormShape } from "../../../../shared/styles/staffFormShape";

/**
 * Style cho modal bảo trì / kiểm định (danh sách thiết bị, chỉnh sửa, xem ảnh).
 * Tách khỏi staffWorkSlotStyles để màn chi tiết gọn và tái sử dụng theo luồng.
 */
export const staffWorkSlotModalStyles = StyleSheet.create({
  maintenanceModalBackdrop: {
    flex: 1,
    backgroundColor: neutral.modalBackdrop,
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  maintenanceModalCard: {
    backgroundColor: neutral.surface,
    borderRadius: staffFormShape.radiusSurface,
    padding: 18,
    maxHeight: "88%",
    width: "100%",
    alignSelf: "center",
    borderCurve: "continuous",
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
  },
  maintenanceModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 12,
  },
  maintenanceModalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: neutral.heading,
    letterSpacing: -0.2,
  },
  maintenanceModalSubtitle: {
    fontSize: 14,
    color: neutral.textSecondary,
    marginBottom: 14,
    lineHeight: 20,
  },
  maintenanceCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: neutral.tileMuted,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: neutral.border,
  },
  maintenanceCloseBtnText: {
    fontSize: 22,
    color: neutral.slate600,
    lineHeight: 24,
    fontWeight: "400",
  },
  floorSortScroll: {
    marginBottom: 10,
  },
  floorSortContent: {
    flexDirection: "row",
    gap: 8,
    paddingRight: 8,
  },
  floorChip: {
    borderRadius: staffFormShape.radiusChip,
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    backgroundColor: neutral.backgroundElevated,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  floorChipSelected: {
    borderColor: brandPrimary,
    backgroundColor: brandTintBg,
  },
  floorChipText: {
    fontSize: 13,
    color: neutral.textBody,
    fontWeight: "600",
  },
  floorChipTextSelected: {
    color: brandPrimary,
  },
  maintenanceHintCard: {
    padding: 14,
    borderRadius: staffFormShape.radiusControl,
    borderWidth: 1,
    borderColor: neutral.border,
    backgroundColor: neutral.backgroundSubtle,
    marginBottom: 12,
  },
  maintenanceHintText: {
    fontSize: 13,
    color: neutral.textSecondary,
    lineHeight: 18,
  },
  maintenanceDraftTitle: {
    fontSize: 14,
    color: brandSecondary,
    fontWeight: "700",
    marginBottom: 8,
    marginTop: 16,
  },
  maintenanceModalBodyScroll: {
    marginBottom: 4,
  },
  modalBodyScrollContent: {
    paddingBottom: 8,
  },
  maintenanceDraftList: {
    marginBottom: 14,
  },
  maintenanceDraftRow: {
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    backgroundColor: neutral.surface,
    borderRadius: staffFormShape.radiusControl,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
    borderCurve: "continuous",
  },
  maintenanceDraftName: {
    fontSize: 15,
    fontWeight: "600",
    color: neutral.text,
  },
  maintenanceDraftMeta: {
    fontSize: 12,
    color: neutral.textMuted,
    marginTop: 4,
  },
  maintenanceActionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  maintenanceSubmitBtn: {
    flex: 1,
    borderRadius: staffFormShape.radiusControl,
    minHeight: 48,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: brandPrimary,
    shadowColor: brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 4,
  },
  maintenanceSubmitBtnDisabled: {
    opacity: 0.65,
  },
  maintenanceSubmitBtnText: {
    color: neutral.surface,
    fontWeight: "700",
    fontSize: 15,
  },
  maintenanceSecondaryBtn: {
    flex: 1,
    borderRadius: staffFormShape.radiusControl,
    minHeight: 48,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    backgroundColor: neutral.surface,
  },
  maintenanceSecondaryBtnText: {
    color: neutral.textBody,
    fontWeight: "700",
    fontSize: 15,
  },
  editAssetModalBackdrop: {
    flex: 1,
    backgroundColor: neutral.modalBackdrop,
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  // Bọc modal chỉnh thiết bị — tránh nhảy layout khi mở bàn phím (đồng bộ staffIssueNote).
  editAssetModalKeyboardAvoid: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
  },
  editAssetModalCard: {
    backgroundColor: neutral.surface,
    borderRadius: staffFormShape.radiusSurface,
    padding: 18,
    maxHeight: "90%",
    borderCurve: "continuous",
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
  },
  editAssetFieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: neutral.slate600,
    marginBottom: 8,
    letterSpacing: 0.15,
  },
  editAssetInput: {
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    borderRadius: staffFormShape.radiusControl,
    backgroundColor: neutral.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: neutral.text,
    marginBottom: 14,
    borderCurve: "continuous",
  },
  editAssetReadonly: {
    backgroundColor: neutral.backgroundSubtle,
    color: neutral.textSecondary,
    borderColor: neutral.border,
  },
  editAssetNoteInput: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  editAssetCameraBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    alignSelf: "stretch",
    borderRadius: staffFormShape.radiusControl,
    borderWidth: 1.5,
    borderColor: brandPrimary,
    backgroundColor: brandTintBg,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 6,
  },
  editAssetCameraBtnDisabled: {
    opacity: 0.5,
  },
  editAssetCameraBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: brandPrimary,
  },
  maintenanceImageThumbWrap: {
    position: "relative",
  },
  maintenanceImageDeleteBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
    alignItems: "center",
    justifyContent: "center",
  },
  maintenanceImageDeleteBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 18,
  },
  inspectionToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  baselineHintMargin: {
    marginBottom: 8,
  },
  modalLoadingCenter: {
    paddingVertical: 16,
    alignItems: "center",
  },
  modalEditorLoadingCenter: {
    paddingVertical: 20,
    alignItems: "center",
  },
  modalLoadingTextMargin: {
    marginTop: 8,
  },
  ticketImagesScroll: {
    maxHeight: 170,
  },
  ticketImagesStrip: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  ticketImageThumb: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
  },
  ticketImageThumbHorizontal: {
    width: 150,
    aspectRatio: 1,
  },
  ticketImage: {
    width: "100%",
    height: "100%",
  },
  ticketImagePressable: {
    flex: 1,
  },
  imageModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  imageModalContent: {
    width: "100%",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#ffffff",
  },
  imageModalClose: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 2,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.75)",
  },
  imageModalCloseText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 20,
  },
  imageModalImage: {
    width: "100%",
    height: 320,
  },
});
